---
ID: "3c718d60-b407-4b3b-8e58-c24659743057"
Parent: "faa91e20-000a-4b9e-94ac-30828d70fbbc"
Template: "faa91e20-000a-4b9e-94ac-30828d70fbbc"
Path: /sitecore/templates/Project/TODO/Page Types/Task Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{07601589-3751-4598-BEC0-BCF81D346A97}">
        <r
          id="{52FDA716-9B80-40BE-BAA9-E74988A8D62C}"
          ph="main"
          uid="{95A02C50-80B3-4BBE-946A-BBF6AC5DA442}" />
        <r
          id="{3F80BDB4-5F00-4275-8FFA-7E05BD33FCA0}"
          ph="sideNav"
          uid="{B7F3D4D5-AF75-4CD0-A1F8-8D18483BCAB1}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200429T173229Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "211b9400-3693-4d51-b465-422181da5f36"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200504T093309Z
